blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

project_show:
  path:	/show
  defaults: {_controller: AppBundle:Default:show}

